#!/bin/sh
DIR=$(dirname "$0")

"$DIR/git/install.sh"
"$DIR/zsh/install.sh"
"$DIR/direnv/install.sh"
"$DIR/code/install.sh"
"$DIR/claude/install.sh"
"$DIR/nushell/install.sh"
"$DIR/brew/install.sh"

echo "Manually install the following"
echo "- Chrome"
echo "- Obsidian"
echo "- Todoist"
echo "- Bitwarden"
echo "- Discord"
echo "- Google Drive"
echo "- WhatsApp"
echo "- Microsoft Remote Desktop"
echo "- Figma"
echo "- Notion"
echo "- Raindrop"
echo "- AltTab"
echo "- SteelSeries Exact Mouse Tool"
echo "- Mionix Hub"
echo "- Logitech G Hub"
